### ISSUE TITLE
`NoSuchMethodError` in `io.javalin.openapi.plugin.DefinitionConfiguration`

### ISSUE THREAD

**Issue by mikera** [javalin/javalin-openapi#233]
I recently encountered the following exception (Javalin `6.3.0`), which occurs when trying to access the swagger UI:

```
[JettyServerThreadPool-165] ERROR io.javalin.Javalin - Fatal error occurred while servicing http-request
java.lang.NoSuchMethodError: 'io.javalin.openapi.plugin.DefinitionConfiguration io.javalin.openapi.plugin.DefinitionConfiguration.withInfo(java.util.function.Consumer)'
	at convex.restapi.RESTServer.lambda$8(RESTServer.java:135)
	at io.javalin.openapi.plugin.OpenApiPlugin$createDocumentation$1.invoke(OpenApiPlugin.kt:36)
	at io.javalin.openapi.plugin.OpenApiPlugin$createDocumentation$1.invoke(OpenApiPlugin.kt:25)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
```

I would expect this not to throw such an exception, because the code compiles fine and the target method apparently exists.

Calling code looks like:

```java
	protected void addOpenApiPlugins(JavalinConfig config) {
		String docsPath="openapi-plugin/openapi-default.json";
		
		config.registerPlugin(new OpenApiPlugin(pluginConfig -> {
                    pluginConfig
                    .withDocumentationPath(docsPath)
                    .withDefinitionConfiguration((version, definition) -> {
                    	DefinitionConfiguration def=definition;
                        def=def.withInfo((Consumer <OpenApiInfo> )info -> {
					info.setTitle("Convex REST API");
					info.setVersion("0.7.0");
                        });
                    });
		}));

		config.registerPlugin(new SwaggerPlugin(swaggerConfiguration->{
			swaggerConfiguration.setDocumentationPath(docsPath);
		}));
		config.registerPlugin(new ReDocPlugin(reDocConfiguration -> {
	        reDocConfiguration.setDocumentationPath(docsPath);
	    }));
		
		for (JsonSchemaResource generatedJsonSchema : new JsonSchemaLoader().loadGeneratedSchemes()) {
	        System.out.println(generatedJsonSchema.getName());
	    }
	}
```

This looks like a bug, though I could be doing something wrong?

**Comment by dzikoysk** [comment]
This function is definitely there:

* https://github.com/javalin/javalin-openapi/blob/main/javalin-plugins/javalin-openapi-plugin/src/main/kotlin/io/javalin/openapi/plugin/OpenApiConfiguration.kt#L55-L57

Maybe you faced some issue with local internal build cache? :thinking: Does it throw when you're launching your code within IDE, or it comes from the final jar?

**Comment by mikera** [comment]
Thanks @dzikoysk ! I think I managed to solve the problem though I'm not entirely sure how. Possibly some interaction with the way that Eclipse handles JPMS modules?

**Comment by dzikoysk** [comment]
It's hard to say, does it still happen on the latest version?

**Comment by mikera** [comment]
It seems fine now thanks @dzikoysk . Happy to close this (unless you want to investigate further)
